/* Creacion de triggers para la tabla FACTURA y DETALLE_FACTURA
Nombre: Ivonne Mendoza
mail: ivonne@imendoza.io
*/


USE COMPRAS;

DESCRIBE FACTURA;

-- DROP TABLE
DROP TABLE IF EXISTS FACTURA_BACKUP;

-- CREA TABLA DE BACKUP
CREATE TABLE FACTURA_BACKUP (
	idBackup INT(11) NOT NULL AUTO_INCREMENT, 
	idFactura INT (11) NOT NULL,
	fecha DATETIME DEFAULT NULL,
	idCliente INT(11) DEFAULT NULL,
	iDEmpleado INT(11) DEFAULT NULL,
	fecha_operacion DATETIME DEFAULT CURRENT_TIMESTAMP,
	tipo_operacion ENUM ('INSERT', 'UPDATE', 'DELETE') NOT NULL,
	usuario VARCHAR(100) DEFAULT NULL,
	PRIMARY KEY (idBackup),
	-- indice opcional en caso de querer acelerar busqueda de empleado
	INDEX idx_idEmpleado (idEmpleado) 
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- DROP TABLE 
DROP TABLE IF EXISTS DETALLE_FACTURA_BACKUP;

-- COLUMNAS DE DETALLE_FACTURA
DESCRIBE DETALLE_FACTURA;

-- CREA TABLA DE BACKUP
CREATE TABLE DETALLE_FACTURA_BACKUP (
	idBackup INT(11) NOT NULL AUTO_INCREMENT,
	idDetalle INT(11) NOT NULL ,
	idFactura INT(11) DEFAULT NULL, 
	idProducto INT(11) DEFAULT NULL,
	precioUnitario DECIMAL(10,2) DEFAULT NULL,
	cantidad INT(11) DEFAULT NULL,
	fecha_operacion DATETIME DEFAULT CURRENT_TIMESTAMP,
	tipo_operacion ENUM ('INSERT', 'UPDATE', 'DELETE') NOT NULL,
	usuario VARCHAR(100) DEFAULT NULL,
	PRIMARY KEY (idBackup),
	-- opcional en caso de querer buscar por idFactura
	INDEX idx_idFactura (idFactura)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- SECCION DE TRIGGER factura


DROP TRIGGER IF EXISTS TRG_FACTURA_AFTER_INSERT;
DROP TRIGGER IF EXISTS TRG_FACTURA_AFTER_UPDATE;
DROP TRIGGER IF EXISTS TRG_FACTURA_AFTER_DELETE;

DELIMITER //

CREATE TRIGGER TRG_FACTURA_AFTER_INSERT
AFTER INSERT ON FACTURA
FOR EACH ROW
BEGIN
	INSERT INTO FACTURA_BACKUP (idFactura, fecha, idCliente, idEmpleado, tipo_operacion, usuario)
	VALUE (NEW.idFactura, NEW.fecha, NEW.idCliente, NEW.idEmpleado, 'INSERT', USER());
END //


CREATE TRIGGER TRG_FACTURA_AFTER_UPDATE
AFTER UPDATE ON FACTURA
FOR EACH ROW
BEGIN
	INSERT INTO FACTURA_BACKUP (idFactura, fecha, idCliente, idEmpleado, tipo_operacion, usuario)
	VALUE (NEW.idFactura, NEW.fecha, NEW.idCliente, NEW.idEmpleado, 'UPDATE', USER());
END //


CREATE TRIGGER TRG_FACTURA_AFTER_DELETE
AFTER DELETE ON FACTURA
FOR EACH ROW
BEGIN
	INSERT INTO FACTURA_BACKUP (idFactura, fecha, idCliente, idEmpleado, tipo_operacion, usuario)
	VALUE (OLD.idFactura, OLD.fecha, OLD.idCliente, OLD.idEmpleado, 'DELETE', USER());
END //



-- TRIGGERS PARA DETALLE FACTURA 
DROP TRIGGER IF EXISTS TRG_DETALLE_FACTURA_AFTER_INSERT //
DROP TRIGGER IF EXISTS TRG_DETALLE_FACTURA_AFTER_UPDATE //
DROP TRIGGER IF EXISTS TRG_DETALLE_FACTURA_AFTER_DELETE //

CREATE TRIGGER TRG_DETALLE_FACTURA_AFTER_INSERT
AFTER INSERT ON DETALLE_FACTURA
FOR EACH ROW
BEGIN
	INSERT INTO DETALLE_FACTURA_BACKUP (idDetalle, idFactura, idProducto, precioUnitario, cantidad, tipo_operacion, usuario)
	VALUE (NEW.idDetalle, NEW.idFactura, NEW.idProducto, NEW.precioUnitario, NEW.cantidad, 'INSERT', USER());
END //

CREATE TRIGGER TRG_DETALLE_FACTURA_AFTER_UPDATE
AFTER UPDATE ON DETALLE_FACTURA
FOR EACH ROW
BEGIN
	INSERT INTO DETALLE_FACTURA_BACKUP (idDetalle, idFactura, idProducto, precioUnitario, cantidad, tipo_operacion, usuario)
	VALUE (NEW.idDetalle, NEW.idFactura, NEW.idProducto, NEW.precioUnitario, NEW.cantidad, 'UPDATE', USER());
END //

CREATE TRIGGER TRG_DETALLE_FACTURA_AFTER_DELETE
AFTER DELETE ON DETALLE_FACTURA
FOR EACH ROW
BEGIN
	INSERT INTO DETALLE_FACTURA_BACKUP (idDetalle, idFactura, idProducto, precioUnitario, cantidad, tipo_operacion, usuario)
	VALUE (OLD.idDetalle, OLD.idFactura, OLD.idProducto, OLD.precioUnitario, OLD.cantidad, 'DELETE', USER());
END //

DELIMITER ;


-- COMPROBACIONES PARA AMBOS TRIGGERS
-- INSERTAR Y ACTUALIZAR UNA FACTURA Y PROBAR EL TRIGGER
INSERT INTO FACTURA (fecha, idCliente, idEmpleado)
VALUES ('2024-01-15 10:30:00', 1, 2);


UPDATE FACTURA 
SET fecha = NOW(), idEmpleado = 4
WHERE idFactura = 20;

-- COMPROBACIONES
SELECT * FROM FACTURA_BACKUP;

-- INSERTAR Y ACTUALIZAR UN DETALLE_FACTURA Y PROBAR EL TRIGGER
INSERT INTO DETALLE_FACTURA (idFactura, idProducto, precioUnitario, cantidad)
VALUES ((SELECT MAX(idFactura) FROM FACTURA), 1, 2.00, 5);


UPDATE DETALLE_FACTURA 
SET cantidad = 10, precioUnitario = 2.50
WHERE idDetalle = 58;

SELECT * FROM DETALLE_FACTURA_BACKUP;
SHOW TRIGGERS FROM COMPRAS;




